language: scala
jdk: oraclejdk8
services:
  - cassandra
matrix:
  include:
  - env: SBT_VERSION="0.13.16"
    scala: 2.10.6
  - env: SBT_VERSION="1.0.3"
    scala: 2.12.3
script:
   - sbt test scripted
